container workflow updates
Signed-off-by: Collin McNeese <collinmcneese@github.com>

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -20,8 +20,11 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+  version-collector:
+    uses: ./.github/workflows/version-collector.yml
   build-and-push-image:
     runs-on: ubuntu-latest
+    needs: version-collector
     permissions:
       contents: read
       packages: write
@@ -36,8 +39,8 @@ jobs:
 
       - name: Prep
         run: |
-          echo Building with Package version ${{ steps.version-collector.outputs.package-version }}
-          (echo ${{ steps.version-collector.outputs.package-version }} | grep -s -q -E '^[0-9]+\.[0-9]+\.[0-9]+$') || (echo "could not determine version!" && exit 1)
+          echo Building with Package version ${{ needs.version-collector.outputs.package-version }}
+          (echo ${{ needs.version-collector.outputs.package-version }} | grep -s -q -E '^[0-9]+\.[0-9]+\.[0-9]+$') || (echo "could not determine version!" && exit 1)
 
       - name: Log in to the Container registry
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
@@ -60,9 +63,9 @@ jobs:
           push: false
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
-            RUNNER_VERSION=${{steps.version-collector.outputs.package-version}}
+            RUNNER_VERSION=${{needs.version-collector.outputs.package-version}}
           tags: |
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{steps.version-collector.outputs.package-version}}
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{needs.version-collector.outputs.package-version}}
 
       - name: Build and push latest main Docker image
         if: github.ref == 'refs/heads/main'
@@ -71,7 +74,7 @@ jobs:
           push: true
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
-            RUNNER_VERSION=${{steps.version-collector.outputs.package-version}}
+            RUNNER_VERSION=${{needs.version-collector.outputs.package-version}}
           tags: |
             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.version-collector.outputs.package-version}}
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{needs.version-collector.outputs.package-version}}
